# -*- coding: utf-8 -*-
"""EPICS.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1q8r4QdIV7jNfJqda2SfLwUSk4lDAwqY2

# Imports
"""

!pip install -q kagglehub tensorflow

import kagglehub
import pandas as pd
import numpy as np

from sklearn.preprocessing import LabelEncoder, MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import (
    accuracy_score, precision_score, recall_score, f1_score
)

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv1D, MaxPooling1D, Dense, Dropout, BatchNormalization, GlobalAveragePooling1D
from tensorflow.keras.callbacks import EarlyStopping, ReduceLROnPlateau

"""# Loading Dataset"""

path = kagglehub.dataset_download("hooong/aviation-maintenance-dataset-from-the-ngafid")
BASE_PATH = path + "/2days/2days/"

header_df = pd.read_csv(BASE_PATH + 'flight_header.csv')
flight_data_dict = pd.read_pickle(BASE_PATH + 'flight_data.pkl')

"""# Dataframe"""

MAX_FLIGHTS = 150
flight_dfs = []

for i, (master_index, data_array) in enumerate(flight_data_dict.items()):
    if i >= MAX_FLIGHTS:
        break
    temp_df = pd.DataFrame(data_array)
    temp_df['Master Index'] = master_index
    flight_dfs.append(temp_df)

flight_df = pd.concat(flight_dfs, ignore_index=True)
df = flight_df.merge(header_df, on='Master Index', how='left')

"""# Preprocessing"""

df.columns = df.columns.astype(str)

if '0' in df.columns:
    df.rename(columns={'0': 'timestep'}, inplace=True)

df['Master Index'] = df['Master Index'].astype('int32')
df['timestep'] = df['timestep'].astype('float32')

df = df.sort_values(['Master Index', 'timestep'])

numeric_cols = df.select_dtypes(include=[np.number]).columns
df[numeric_cols] = df[numeric_cols].astype('float32')


df[numeric_cols] = df.groupby('Master Index')[numeric_cols].ffill()
df[numeric_cols] = df.groupby('Master Index')[numeric_cols].bfill()
df.fillna(0, inplace=True)


cat_cols = df.select_dtypes(include=['object']).columns
for col in cat_cols:
    df[col] = LabelEncoder().fit_transform(df[col].astype(str))

"""# Targets"""

df['target_reg'] = df['date_diff']

threshold = df['target_reg'].quantile(0.25)
df['target_class'] = (df['target_reg'] <= threshold).astype(int)

"""# Train/Test Split"""

unique_ids = df['Master Index'].unique()

train_ids, test_ids = train_test_split(unique_ids, test_size=0.2, random_state=42)

train_df = df[df['Master Index'].isin(train_ids)].copy()
test_df = df[df['Master Index'].isin(test_ids)].copy()

"""# Feature Selection"""

exclude_cols = ['Master Index', 'target_class', 'target_reg']
feature_cols = [c for c in df.columns if c not in exclude_cols]

corr = train_df.corr()['target_reg'].abs().sort_values(ascending=False)
top_features = [c for c in corr.index[1:26] if c in feature_cols]

"""# Scaling"""

scaler = MinMaxScaler()

train_df[top_features] = scaler.fit_transform(train_df[top_features])
test_df[top_features] = scaler.transform(test_df[top_features])

target_scaler = MinMaxScaler()

train_df['target_reg_scaled'] = target_scaler.fit_transform(train_df[['target_reg']])
test_df['target_reg_scaled'] = target_scaler.transform(test_df[['target_reg']])


full_df = pd.concat([train_df, test_df]).sort_values(['Master Index', 'timestep'])

full_df['target_reg_scaled'] = target_scaler.transform(full_df[['target_reg']])

"""# Create Sequences"""

def create_sequences(X, y, seq_len=20):
    X_seq, y_seq = [], []
    for i in range(len(X) - seq_len):
        X_seq.append(X.iloc[i:i+seq_len].values)
        y_seq.append(y.iloc[i+seq_len])
    return np.array(X_seq), np.array(y_seq)

SEQ_LEN = 20
X_train_cnn, y_train_cnn = create_sequences(train_df[top_features], train_df['target_reg_scaled'])
X_test_cnn, y_test_cnn = create_sequences(test_df[top_features], test_df['target_reg_scaled'])

X_full_cnn, y_full_cnn = create_sequences(full_df[top_features], full_df['target_reg_scaled'])

"""# Regression - CNN Model"""

cnn_reg = Sequential([
    Conv1D(128, 5, activation='relu', padding='same', input_shape=(SEQ_LEN, len(top_features))),
    BatchNormalization(),
    MaxPooling1D(2),

    Conv1D(128, 3, activation='relu', padding='same'),
    BatchNormalization(),
    MaxPooling1D(2),

    Conv1D(64, 3, activation='relu', padding='same'),
    BatchNormalization(),

    GlobalAveragePooling1D(),

    Dense(128, activation='relu'),
    Dropout(0.4),
    Dense(64, activation='relu'),
    Dense(1)
])

cnn_reg.compile(optimizer='adam', loss='huber')

cnn_reg.fit(
    X_train_cnn, y_train_cnn,
    epochs=20,
    batch_size=32,
    validation_split=0.2,
    callbacks=[
        EarlyStopping(patience=8, restore_best_weights=True),
        ReduceLROnPlateau(patience=3)
    ],
    verbose=1
)

"""# Predict RUL"""

y_full_pred = cnn_reg.predict(X_full_cnn)


y_full_pred = target_scaler.inverse_transform(y_full_pred.reshape(-1, 1)).flatten()


y_full_pred = np.maximum(y_full_pred, 0)

"""# Align and Filter"""

aligned_full_df = full_df.iloc[SEQ_LEN:].copy()
aligned_full_df['predicted_RUL'] = y_full_pred
all_engines_rul = aligned_full_df.groupby('Master Index')['predicted_RUL'].mean().reset_index()
RUL_THRESHOLD = aligned_full_df['predicted_RUL'].quantile(0.25)

low_rul_df = aligned_full_df[
    aligned_full_df['predicted_RUL'] <= RUL_THRESHOLD
]

"""# Prepare RF Dataset"""

rf_features = low_rul_df.groupby('Master Index')[top_features].mean()

rf_target = low_rul_df.groupby('Master Index')['target_class'].max()

rf_df = rf_features.copy()
rf_df['target_class'] = rf_target
rf_df = rf_df.reset_index()

"""# Training Random Forest"""

X = rf_df.drop(columns=['Master Index', 'target_class'])
y = rf_df['target_class']

X_train_rf, X_test_rf, y_train_rf, y_test_rf = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

rf_model = RandomForestClassifier(
    n_estimators=100,
    max_depth=6,
    min_samples_split=20,
    min_samples_leaf=10,
    class_weight='balanced',
    random_state=42
)

rf_model.fit(X_train_rf, y_train_rf)


y_pred_rf_test = rf_model.predict(X_test_rf)


rf_predictions = rf_model.predict(X)

rf_results = rf_df[['Master Index']].copy()
rf_results['Health_Status'] = rf_predictions


rul_results = aligned_full_df.groupby('Master Index')['predicted_RUL'].mean().reset_index()


final_results = pd.merge(
    all_engines_rul,
    rf_results,
    on='Master Index',
    how='left'
)


final_results['Health_Status'] = final_results['Health_Status'].fillna(0)


final_results['Health_Status'] = final_results['Health_Status'].map({
    0: 'Healthy',
    1: 'Needs Maintenance'
})

print(final_results.head())

"""# Evaluation"""

y_pred_rf = rf_model.predict(X_test_rf)

print("===== FINAL PIPELINE RESULTS =====")
print("Accuracy :", accuracy_score(y_test_rf, y_pred_rf))
print("Precision:", precision_score(y_test_rf, y_pred_rf))
print("Recall   :", recall_score(y_test_rf, y_pred_rf))
print("F1 Score :", f1_score(y_test_rf, y_pred_rf))

"""# Dashboard"""

dashboard_df = final_results.copy()


dashboard_df.rename(columns={
    'Master Index': 'id',
    'predicted_RUL': 'rul',
    'Health_Status': 'status'
}, inplace=True)


dashboard_df['name'] = dashboard_df['id'].apply(lambda x: f"Engine {int(x)}")


dashboard_df['status'] = dashboard_df['status'].map({
    'Healthy': 'Good',
    'Needs Maintenance': 'Critical'
})


dashboard_df = dashboard_df[['id', 'name', 'rul', 'status']]

print(dashboard_df.head())

dashboard_df.to_json("engines.json", orient="records")

from google.colab import files
files.download("engines.json")